### ISSUE TITLE
PlatON Ecosystem Building Invitation-A Privacy-Preserving AI Network

### ISSUE THREAD

**Issue by biganxin** [PatrickAlphaC/PatrickAlphaC#1]
Sorry to interrupt you.

We are looking for developer ambassadors to participate in efforts such as Platon/Alaya network building and developer community training and education.
If you are interested please establish contact with me.

Contact：
Discord：https://discord.gg/jAjFzJ3Cff （@Boney2）
Dev-Telegram：https://t.me/joinchat/LhO63AsZ_iozZGNl （@@Boneybi）

**Comment by PatrickAlphaC** [comment]
Amazing!!! @biganxin!! Excited to work together!

**Comment by westonnelson** [comment]
😁
