### ISSUE TITLE
Mentorship

### ISSUE THREAD

**Issue by Ghost-general** [PatrickAlphaC/PatrickAlphaC#2]
Saw your video on solidity on youtube, got  blown away.. Hope you don't mind sharing a good pdf for me to help sharpen my skills and for reference purpose... I'm in Africa and I need to help my self and a whole lot of people believe in my dream

**Comment by PatrickAlphaC** [comment]
Glad it helped! 

You can check out my post on the best places to learn web3!

https://dev.to/patrickalphac/top-10-smart-contract-solidity-developer-learning-resources-46db
